"""Add license plate to cars

Revision ID: 1c18f53f051e
Revises: 531a62540997
Create Date: 2026-07-27 23:01:45.197398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c18f53f051e'
down_revision = '531a62540997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_plate', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['license_plate'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('license_plate')

    # ### end Alembic commands ###
