"""Update model table

Revision ID: 4a2c0c853b02
Revises: 640ccd87ff4a
Create Date: 2026-08-06 12:04:11.129109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2c0c853b02'
down_revision = '640ccd87ff4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'brand_id', name='uq_model_brand')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_column('logo_public_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_public_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    op.drop_table('models')
    # ### end Alembic commands ###
