"""Create car image table

Revision ID: 531a62540997
Revises: 33a2cf60dd14
Create Date: 2026-07-27 11:35:36.060804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531a62540997'
down_revision = '33a2cf60dd14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_images',
    sa.Column('car_id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_images')
    # ### end Alembic commands ###
