"""Update refresh tokens table

Revision ID: 640ccd87ff4a
Revises: af28f3e92ccc
Create Date: 2026-07-30 10:10:15.444703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640ccd87ff4a'
down_revision = 'af28f3e92ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('refresh_tokens_token_hash_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.create_unique_constraint(batch_op.f('refresh_tokens_token_hash_key'), ['token_hash'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
