"""add model relationship to cars.

Revision ID: 94c0e7557c32
Revises: 4a2c0c853b02
Create Date: 2026-08-13 12:02:57.577392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c0e7557c32'
down_revision = '4a2c0c853b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'models', ['model_id'], ['id'])
        batch_op.drop_column('model')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('model_id')

    # ### end Alembic commands ###
