"""Create fuel types table

Revision ID: 9def44b750d3
Revises: 077c8dbabc3b
Create Date: 2026-07-27 11:16:51.103133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9def44b750d3'
down_revision = '077c8dbabc3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_types',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fuel_types')
    # ### end Alembic commands ###
