"""Remove unique model brand constraint

Revision ID: eb8a01349d98
Revises: 94c0e7557c32
Create Date: 2026-08-19 09:27:40.608953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8a01349d98'
down_revision = '94c0e7557c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_model_brand'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_model_brand'), ['name', 'brand_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
